console.log("hello there".toUpperCase())
console.log("   Hello There  ".trim())
console.log(Math.random())
console.log(Math.round(Math.random()*10))
//console.log(Math.ceil(.8.1)
console.log("  |  |  ")
console.log("  |  |  ")
console.log("  |  |  ")
console.log("--------")
console.log("  |  |  ")
console.log("  |  |  ")
console.log("  |  |  ")
console.log("--------")
console.log("  |  |  ")
console.log("  |  |  ")
console.log("  |  |  ")
